name: Publish BambooApi

on: workflow_dispatch
    push:
        paths:
            - 'Modules/BambooApi/**'
jobs:
    build:
      name: Publish
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Publish
          env:
            APIKEY: ${{ secrets.POSH_GALLERY_API_KEY }}
          run: ./Modules/Publish.ps1 -TargetFolder "BambooApi"
          shell: pwsh