name: Publish HubSpotApi

on:
    push:
        paths:
            - 'Modules/HubSpotApi/**'
jobs:
    build:
      name: Publish
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Publish
          env:
            APIKEY: ${{ secrets.POSH_GALLERY_API_KEY }}
          run: ./Modules/Publish.ps1 -TargetFolder "HubSpotApi"
          shell: pwsh